<script lang="ts">
	import { HttpRegex } from '@utils/regex';
	import type { BaseProps } from '@utils/types';
	import imageManifest from '@data/generated/image-manifest.json';

	// Must match the formats generated by the image-transmutation step in the CMS build workflow
	const FORMATS = ['webp', 'png'];

	type ImageManifestEntry = {
		width: number;
		height: number;
		hasOptimized: boolean;
		availableWidths: string[];
	};

	const manifest = imageManifest as Record<string, ImageManifestEntry>;

	export type ImageProps = BaseProps & {
		src: string;
		alt: string;
		figcaption?: string;
		lazy?: boolean;
		sizes?: string;
		width?: string | number;
		height?: string | number;
	};

	let {
		src,
		alt,
		figcaption,
		lazy = true,
		sizes: explicitSizes,
		width: explicitWidth,
		height: explicitHeight,
		class: className,
		...props
	} : ImageProps = $props();

	let fileName = src ? src.split('.')[0] : '';
	let usesResponsiveWidths = false;
	let imgWidth: number | undefined;
	let imgHeight: number | undefined;
	let srcSet = buildSrcset();

	// An explicitly-passed width/height (e.g. AuthorAvatar's fixed circular sizing) always wins
	// over the manifest-derived intrinsic dimensions
	let finalWidth = $derived(explicitWidth ?? imgWidth);
	let finalHeight = $derived(explicitHeight ?? imgHeight);

	let computedSizes = $derived(explicitSizes ?? (usesResponsiveWidths && lazy ? 'auto' : ''));

	function buildSrcset() {
		if (HttpRegex.test(src)) return;

		// Only build srcset if files are png, jpg, jpeg, webp or avif
		if (!src.match(/\.(png|jpe?g|webp|avif)$/)) return;

		// The image manifest is generated automatically (image-manifest.mjs)
		// and contains image info like sizes and whether or not they exist on disk
		const manifestEntry = manifest[src];

		if (manifestEntry) {
			imgWidth = manifestEntry.width;
			imgHeight = manifestEntry.height;
		}

		if (!manifestEntry?.hasOptimized) {
			return;
		}

		// If src is the cms/media folder, replace it with cms/optimized-media
		// "cms/media" must be in the beginning of the string (with or without a leading slash)
		src = src.replace(/^\/?cms\/media/, '/cms/optimized-media');
		fileName = fileName.replace(/^\/?cms\/media/, '/cms/optimized-media');

		// Replace .jpg or .jpeg extensions with .png for optimized media
		src = src.replace(/\.jpe?g$/i, '.png');
		fileName = fileName.replace(/\.jpe?g$/i, '.png');

		let srcset = '';

		// Only use width-based candidates when the browser can actually pick the right one:
		// either the image is lazy (so "sizes=auto" kicks in) or the caller told us the
		// rendered size via `sizes`. Otherwise, a wrongly-sized image could be requested
		// (e.g. a small eager avatar defaulting to the "sizes=100vw" spec fallback).
		if (manifestEntry.availableWidths.length > 0 && (lazy || explicitSizes)) {
			usesResponsiveWidths = true;

			const widths = manifestEntry.availableWidths;

			for (let i = 0; i < widths.length; i++) {
				srcset += `${fileName}-${widths[i]}w.${FORMATS[0]} ${widths[i]}w`;

				if (i < widths.length - 1) {
					srcset += ', ';
				}
			}

			// Point the fallback `src` (used by browsers without srcset/sizes support) at the
			// full-size original, since we can't know what size they'll actually render at
			src = `${fileName}.${FORMATS[1]}`;
		} else {
			for (let i = 0; i < FORMATS.length; i++) {
				srcset += `${fileName}.${FORMATS[i]}`;

				if (i < FORMATS.length - 1) {
					srcset += ', ';
				}
			}
		}

		return srcset;
	}
</script>

{#if src}
	{#if figcaption}
		<figure class={['a-image', className]} {...props}>
			<img
				srcset={srcSet}
				sizes={computedSizes}
				{src}
				{alt}
				width={finalWidth}
				height={finalHeight}
				loading={lazy ? 'lazy' : 'eager'}
				decoding="async"
			/>
			<figcaption>{@html figcaption}</figcaption>
		</figure>
	{:else}
		<img
			srcset={srcSet}
			sizes={computedSizes}
			{src}
			{alt}
			width={finalWidth}
			height={finalHeight}
			loading={lazy ? 'lazy' : 'eager'}
			decoding="async"
			class={['a-image', className]}
			{...props}
		/>
	{/if}
{/if}

<style lang="scss">
	img,
	figure {
		width: 100%;
		height: 100%;
		object-fit: contain;
	}
</style>
