<script lang="ts">
	import { HttpRegex } from '@utils/regex';
	import type { BaseProps } from '@utils/types';
	import imageManifest from '@data/generated/image-manifest.json';

	// Must match the formats generated by the image-transmutation step in the CMS build workflow
	const FORMATS = ['webp', 'jpg'];

	// Must match --maxWidth in the image-transmutation step
	const MAX_WIDTH = 2000;

	type ImageManifestEntry = {
		width: number;
		height: number;
		hasOptimized: boolean;
		availableWidths: string[];
	};

	const manifest = imageManifest as Record<string, ImageManifestEntry>;

	export type ImageProps = BaseProps & {
		src: string;
		alt: string;
		figcaption?: string;
		lazy?: boolean;
		sizes?: string;
		width?: string | number;
		height?: string | number;
	};

	let {
		src: originalSrc,
		alt,
		figcaption,
		lazy = true,
		sizes: explicitSizes,
		width: explicitWidth,
		height: explicitHeight,
		class: className,
		...props
	} : ImageProps = $props();

	let image = $derived(buildImage(originalSrc, lazy, explicitSizes));
	let src = $derived(image.src);
	let srcSet = $derived(image.srcSet);

	// An explicitly-passed width/height (e.g. AuthorAvatar's fixed circular sizing) always wins
	// over the manifest-derived intrinsic dimensions
	let finalWidth = $derived(explicitWidth ?? image.width);
	let finalHeight = $derived(explicitHeight ?? image.height);

	let computedSizes = $derived(explicitSizes ?? (image.usesResponsiveWidths && lazy ? 'auto' : ''));

	let classList = $derived(['a-image', className]);
	let intrinsicWidth = $derived(image.width ? `${image.width}px` : undefined);

	function buildImage(src: string, lazy: boolean, explicitSizes?: string) {
		let fileName = src ? src.split('.')[0] : '';
		const result: {
			src: string;
			srcSet?: string;
			width?: number;
			height?: number;
			usesResponsiveWidths: boolean;
		} = { src, usesResponsiveWidths: false };

		if (!src || HttpRegex.test(src)) return result;

		// Only build srcset if files are png, jpg, jpeg, webp or avif
		if (!src.match(/\.(png|jpe?g|webp|avif)$/)) return result;

		// The image manifest is generated automatically (image-manifest.mjs)
		// and contains image info like sizes and whether or not they exist on disk
		const manifestEntry = manifest[src];

		if (manifestEntry) {
			result.width = manifestEntry.width;
			result.height = manifestEntry.height;
		}

		if (!manifestEntry?.hasOptimized) {
			return result;
		}

		// If src is the cms/media folder, replace it with cms/optimized-media
		// "cms/media" must be in the beginning of the string (with or without a leading slash)
		src = src.replace(/^\/?cms\/media/, '/cms/optimized-media');
		fileName = fileName.replace(/^\/?cms\/media/, '/cms/optimized-media');

		// Replace the source extension with .jpg, the optimized fallback format
		src = src.replace(/\.(png|jpe?g|webp|avif)$/i, '.jpg');
		fileName = fileName.replace(/\.(png|jpe?g|webp|avif)$/i, '.jpg');

		let srcset = '';

		// Only use width-based candidates when the browser can actually pick the right one:
		// either the image is lazy (so "sizes=auto" kicks in) or the caller told us the
		// rendered size via `sizes`. Otherwise, a wrongly-sized image could be requested
		// (e.g. a small eager avatar defaulting to the "sizes=100vw" spec fallback).
		if (manifestEntry.availableWidths.length > 0 && (lazy || explicitSizes)) {
			result.usesResponsiveWidths = true;

			const widths = manifestEntry.availableWidths;

			for (let i = 0; i < widths.length; i++) {
				srcset += `${fileName}-${widths[i]}w.${FORMATS[0]} ${widths[i]}w`;

				if (i < widths.length - 1) {
					srcset += ', ';
				}
			}

			// The full-size file is capped at MAX_WIDTH by image-transmutation.
			// Offer it as the largest candidate so big/retina viewports aren't
			// stuck with the smallest width variant, without duplicating files.
			const fullWidth = Math.min(manifestEntry.width, MAX_WIDTH);
			if (!widths.includes(String(fullWidth))) {
				srcset += `, ${fileName}.${FORMATS[0]} ${fullWidth}w`;
			}

			// Point the fallback `src` (used by browsers without srcset/sizes support) at the
			// full-size original, since we can't know what size they'll actually render at
			src = `${fileName}.${FORMATS[1]}`;
		} else {
			for (let i = 0; i < FORMATS.length; i++) {
				srcset += `${fileName}.${FORMATS[i]}`;

				if (i < FORMATS.length - 1) {
					srcset += ', ';
				}
			}
		}

		result.src = src;
		result.srcSet = srcset;
		return result;
	}
</script>

{#if src}
	{#if figcaption}
		<figure class={classList} {...props}>
			<img
				srcset={srcSet}
				sizes={computedSizes}
				{src}
				{alt}
				width={finalWidth}
				height={finalHeight}
				loading={lazy ? 'lazy' : 'eager'}
				decoding="async"
				style:--image-intrinsic-width={intrinsicWidth}
			/>
			<figcaption>{@html figcaption}</figcaption>
		</figure>
	{:else}
		<img
			srcset={srcSet}
			sizes={computedSizes}
			{src}
			{alt}
			width={finalWidth}
			height={finalHeight}
			loading={lazy ? 'lazy' : 'eager'}
			decoding="async"
			style:--image-intrinsic-width={intrinsicWidth}
			class={classList}
			{...props}
		/>
	{/if}
{/if}

<style lang="scss">
	img,
	figure {
		width: 100%;
		height: 100%;
		object-fit: contain;
	}
</style>
